In [43]:
import numpy as np

## The problem
The idea of this homework is to use a dataset to train the single layer perceptron to learn this pattern. You should classify whether a person will earn or not a salary increase.

In [44]:
inputs = np.array([[18,2], [20,3], [21, 4],  
                   [35,15], [36,16], [38, 18]])

In [45]:
outputs = np.array([0, 0, 0, 1, 1, 1])

Class "0" (zero) indicates a person won't earn a salary increase, otherwise, class "1" (one) indicates a person will earn a salary increase

After training the single layer perceptron, use the new instances below to make predictions. Will the instances below be classified 0 or 1?

In [46]:
test_inputs = np.array([[17,5], [25,8],  
                        [45,10], [31,20]])

Hint: you will need to normalize the inputs in order to train the neural network. You can use the MinMaxScaler from sklearn library

In [59]:
import pandas as pd
df1 = pd.DataFrame(data=inputs, columns=["age", "educational"])
df1

age  educational
0   18            2
1   20            3
2   21            4
3   35           15
4   36           16
5   38           18

## Solution
### Normalizing inputs

In [47]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
inputs_scaled = scaler.fit_transform(inputs)
inputs_scaled

array([[0.    , 0.    ],
       [0.1   , 0.0625],
       [0.15  , 0.125 ],
       [0.85  , 0.8125],
       [0.9   , 0.875 ],
       [1.    , 1.    ]])

### Activation Function

In [48]:
def step_function(sum):
    if sum >= 1:
        return 1
    else:
        return 0

### Forward Pass

In [49]:
def forward_pass(data, weights):
    s = data.dot(weights)
    return step_function(s)

### Training

In [50]:
weights = np.array([0.0, 0.0]) # initializing in cero
samples = len(outputs)
learning_rate = 0.1

def train():
    total_error = 1
    while (total_error != 0): # epochs
        total_error = 0
        for i in range(samples): # instances
            prediction = forward_pass(inputs_scaled[i], weights)
            error = abs(outputs[i] - prediction)
            total_error += error
            if error > 0:
                for j in range(len(weights)):
                    weights[j] += learning_rate * (error * inputs_scaled[i][j])
                    print(f"Weight updated: {weights[j]}")
        print(f"Total Error: {total_error}")

train()

Weight updated: 0.085
Weight updated: 0.08125
Weight updated: 0.17500000000000002
Weight updated: 0.16875
Weight updated: 0.275
Weight updated: 0.26875000000000004
Total Error: 3
Weight updated: 0.36000000000000004
Weight updated: 0.35000000000000003
Weight updated: 0.45000000000000007
Weight updated: 0.43750000000000006
Weight updated: 0.55
Weight updated: 0.5375000000000001
Total Error: 3
Weight updated: 0.635
Weight updated: 0.6187500000000001
Total Error: 1
Total Error: 0


In [51]:
weights

array([0.635  , 0.61875])

### Predictions/Classification

In [52]:
test_inputs

array([[17,  5],
       [25,  8],
       [45, 10],
       [31, 20]])

In [53]:
test_inputs_scaled = scaler.transform(test_inputs)
test_inputs_scaled

array([[-0.05  ,  0.1875],
       [ 0.35  ,  0.375 ],
       [ 1.35  ,  0.5   ],
       [ 0.65  ,  1.125 ]])

In [54]:
test_inputs_scaled[0]

array([-0.05  ,  0.1875])

Prediction of salary increases based on the age and educational score

In [62]:
for i in range(test_inputs_scaled.shape[0]):
    print(test_inputs[i],'->', forward_pass(test_inputs_scaled[i], weights))


[17  5] -> 0
[25  8] -> 0
[45 10] -> 1
[31 20] -> 1
